title: Alexander Chai
logo: /assets/me circle.png

description: Ambitious and high-achieving high school student who excels academically and demonstrates leadership through extra-curricular activities. 

author:

show_downloads: true
theme: jekyll-theme-minimal
